server:
  port: 7001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuqilei-code/0708
          search-paths: src/main/resources
          username: wuqilei-code
          password: 1323687082wu
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/