server:
  port: 9001
spring:
  thymeleaf:
    cache: false
  application:
    name: userweb01
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/
