server:
  port: 8002

spring:
  application:
    name: provider01
  datasource:
    url: jdbc:mysql://localhost:3306/class_0708?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

